name: Docker

on:
  - workflow_dispatch

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      env:
        API_URL: some-url.com
      ports:
        - 80
    steps:
      - name: Log node & OS versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env variable
        run: echo "API_URL is $API_URL"
